cfg: E:/YOffleNet/models/yolov4s-mish.yaml
data: E:/YOffleNet/data/hkim.yaml
hyp: ''
epochs: 300
batch_size: 8
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
weights: ''
name: ''
device: ''
multi_scale: false
single_cls: false
sync_bn: false
local_rank: -1
total_batch_size: 8
world_size: 1
